# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'layo.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_YTMP3(object):
    def setupUi(self, YTMP3):
        YTMP3.setObjectName("YTMP3")
        YTMP3.resize(725, 509)
        YTMP3.setMinimumSize(QtCore.QSize(725, 509))
        YTMP3.setMaximumSize(QtCore.QSize(725, 509))
        self.centralwidget = QtWidgets.QWidget(YTMP3)
        self.centralwidget.setObjectName("centralwidget")
        self.btnConvert = QtWidgets.QPushButton(self.centralwidget)
        self.btnConvert.setGeometry(QtCore.QRect(550, 230, 93, 41))
        self.btnConvert.setStyleSheet("font: 10pt \"Arial\";\n"
"background-color: rgb(85, 170, 255);\n"
"color: rgb(255, 255, 255);")
        self.btnConvert.setObjectName("btnConvert")
        self.inputLink = QtWidgets.QLineEdit(self.centralwidget)
        self.inputLink.setGeometry(QtCore.QRect(80, 230, 451, 41))
        self.inputLink.setStyleSheet("font: 75 10pt \"Arial\";\n"
"color: rgb(85, 170, 255);\n"
"border-color: rgb(85, 170, 255);")
        self.inputLink.setText("")
        self.inputLink.setObjectName("inputLink")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 205, 171, 21))
        self.label.setStyleSheet("font: 75 10pt \"Arial\";")
        self.label.setObjectName("label")
        self.lbResult = QtWidgets.QLabel(self.centralwidget)
        self.lbResult.setGeometry(QtCore.QRect(120, 350, 451, 71))
        self.lbResult.setStyleSheet("color: rgb(85, 170, 127);\n"
"font: 16pt \"Arial\";")
        self.lbResult.setText("")
        self.lbResult.setObjectName("lbResult")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 70, 611, 81))
        self.label_2.setStyleSheet("color: rgb(85, 170, 255);\n"
"font: 75 30pt \"Impact\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(550, 470, 161, 20))
        self.label_3.setStyleSheet("color: rgb(85, 170, 255);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(270, 70, 191, 81))
        self.label_4.setStyleSheet("font: 75 30pt \"Impact\";\n"
"color: rgb(255, 0, 0);")
        self.label_4.setObjectName("label_4")
        YTMP3.setCentralWidget(self.centralwidget)

        self.retranslateUi(YTMP3)
        QtCore.QMetaObject.connectSlotsByName(YTMP3)

    def retranslateUi(self, YTMP3):
        _translate = QtCore.QCoreApplication.translate
        YTMP3.setWindowTitle(_translate("YTMP3", "YT-MP3"))
        self.btnConvert.setText(_translate("YTMP3", "Converter"))
        self.label.setText(_translate("YTMP3", "Insira o Link Youtube:"))
        self.label_2.setToolTip(_translate("YTMP3", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.label_2.setText(_translate("YTMP3", "Converter                       para MP3"))
        self.label_3.setText(_translate("YTMP3", "Develop By Fábio Carvalho"))
        self.label_4.setToolTip(_translate("YTMP3", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.label_4.setText(_translate("YTMP3", "YouTube"))
